### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by RC810** [ilyaglow/thehive-scripts#5]
Heya,

Thanks for writing this first of all! There's a dire need to be able to export reports and for some reason they haven't baked it into TheHive natively yet. I tried the script out on my instance of the hive (version 4.1) and it's erroring out with the following message:

`$ python3 case2pdf.py -s http://localhost:9000 -u <snip> -p <snip> -c ~15982648 -o testexport.pdf
Traceback (most recent call last):
  File "case2pdf.py", line 177, in <module>
    if the_hive.case_to_pdf(args.case, args.output):
  File "case2pdf.py", line 159, in case_to_pdf
    case_md = self.fetch_case(case_id)
  File "case2pdf.py", line 102, in fetch_case
    observables = self.fetch_observables(case_id)
  File "case2pdf.py", line 125, in fetch_observables
    observables_markdown += u'{} | {} | {} | {}'.format(artifact['data'],
KeyError: 'data'
`

Any insight into this would be appreciated! I'm running Ubuntu 20.04 with Python 3.8 for reference.

**Comment by ilyaglow** [comment]
Hey,

Sad so say, but I wrote this script almost 5 years ago, when TheHive API (version 2) was different and I actually had TheHive in my incident response stack. Now, this repo is not essentially supported anymore and I should archive it, so people won't spend time trying to run this.

If you feel comfortable with Python, you can try to fix it by replacing [TheHiveExtendedApi class and calls to it](https://github.com/ilyaglow/thehive-scripts/blob/master/case-to-pdf/case2pdf.py#L31) with a [proper TheHive4py one](https://github.com/TheHive-Project/TheHive4py/tree/1.x), which should work.
